## Отправить изображение

POST http://localhost:1337/users/65784f20f8f4d1ca5ecc1650/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/amigo/Desktop/test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Создать пользователя
POST http://localhost:1337/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "exist3@yandex.ru",
  "firstname": "Ilya",
  "type": "Base",
  "password": "password"
}

###

## Логин пользователя

POST http://localhost:1337/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "exist3@yandex.ru",
  "password": "password"
}

###

###

## Проверить токен пользователя
GET http://localhost:1337/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RhdmF2dGFyOTJAeWFuZGV4LnJ1IiwiZmlyc3RuYW1lIjoiSWx5YSIsImlkIjoiNjU5NTU1MDYwOWQyZGM0OGY1OTUzMWRjIiwiaWF0IjoxNzA0Mjg1NzI1LCJleHAiOjE3MDQ0NTg1MjV9.MaA-axf-ptdl2r-MeOxf3W2Ni-XYbuWnBqpSbdT3rRU